
default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:293534610762:android:01748cd85e6a99b833bdb3",
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
        testers: "ganaelhosaraty3@gmail.com",
        release_notes: "First Fastlane firebase distribution",
        upload_timeout: 600,
  )
  end
end
